"""Build and execute the Phase 1 notebook using Python's standard library.

Notebook code cells use pandas. Captured outputs come from actual execution.
This avoids requiring nbformat/nbclient, which are unavailable locally.
"""
from contextlib import redirect_stdout
from io import StringIO
from pathlib import Path
import json
import textwrap
import traceback

ROOT = Path(__file__).resolve().parent
cells = []


def markdown(source):
    cells.append({"cell_type": "markdown", "metadata": {},
                  "source": textwrap.dedent(source).strip() + "\n"})


def code(source):
    cells.append({"cell_type": "code", "metadata": {}, "execution_count": None,
                  "outputs": [], "source": textwrap.dedent(source).strip() + "\n"})


markdown('''
# AI Dependency and Cognitive Offloading Among University Students:
# An Explainable Machine Learning Study

## Phase 1 — Data loading and audit

**Objective:** inspect the supplied CSV before cleaning, scoring, statistical
analysis, or modeling. These are self-reported survey responses; they do not
objectively measure intelligence, memory, or cognitive ability.

Run the notebook from the project folder. All outputs below were generated by
executing the code cells sequentially in a shared Python namespace. The build
script uses standard-library output capture because `nbformat` and `nbclient`
are unavailable in the current environment. No results are simulated.
''')
code('''
from pathlib import Path
import hashlib
import platform
import pandas as pd

dataset_path = Path("_(AI_Cognitive_Dependence_Survey_Data_BD_StudentsResponses) - Sheet1.csv")
if not dataset_path.is_file():
    raise FileNotFoundError(f"Place the CSV in the notebook working folder: {Path.cwd()}")

df = pd.read_csv(dataset_path)
print("Dataset:", dataset_path.name)
print("SHA-256:", hashlib.sha256(dataset_path.read_bytes()).hexdigest())
print("Python:", platform.python_version())
print("pandas:", pd.__version__)
print("Shape:", df.shape)
print("\\nFirst five rows (transposed for readability):")
print(df.head(5).T.to_string())
print("\\nColumn names:")
for number, column in enumerate(df.columns, start=1):
    print(f"{number:2}. {column}")
print("\\nDataframe information:")
df.info()
print("\\nData types:")
print(df.dtypes.to_string())
print("\\nDescriptive statistics (all columns):")
print(df.describe(include="all").T.to_string())
''')
markdown('''
**Reading the output:** the first five records are transposed only for display;
the dataframe is unchanged. Numeric summaries describe Age. For text columns,
`unique`, `top`, and `freq` describe distinct labels and the most frequent label.
`NaN` in an inapplicable descriptive-statistics field is not a missing response.

## Missingness, duplicate records, and observed labels

**Objective:** print missingness, exact duplicate counts, and every observed
response label before specifying a Likert encoding. Blank strings and whitespace
are checked separately because they may not be represented as pandas nulls.
''')
code('''
missing_counts = df.isna().sum()
duplicate_count = int(df.duplicated().sum())
duplicate_participants = int(df.duplicated(keep=False).sum())
unique_record_count = len(df.drop_duplicates())
print("Missing values per column:")
print(missing_counts.to_string())
print("Total missing cells:", int(missing_counts.sum()))
print("Duplicate rows beyond the first occurrence:", duplicate_count)
print("Rows belonging to duplicate groups (including first occurrences):", duplicate_participants)
print("Distinct complete row patterns:", unique_record_count)
print("Duplicate proportion beyond first occurrences:", f"{duplicate_count / len(df):.2%}")

print("\\nUnique values and frequencies for EVERY column:")
for column in df.columns:
    print(f"\\n{column}")
    print("Unique values:", [repr(value) for value in df[column].unique()])
    print(df[column].value_counts(dropna=False).to_string())

text_columns = df.select_dtypes(include=["object", "string"]).columns
blank_counts = pd.Series({
    column: int(df[column].str.fullmatch(r"\\s*", na=False).sum())
    for column in text_columns
}, name="blank_strings")
whitespace_counts = pd.Series({
    column: int((df[column].notna() & df[column].ne(df[column].str.strip())).sum())
    for column in text_columns
}, name="surrounding_whitespace")
print("\\nText formatting checks:")
print(pd.concat([blank_counts, whitespace_counts], axis=1).to_string())
''')
markdown('''
**Reading the output:** duplicate counts refer to matching values across all
30 columns, not verified duplicate people. There is no respondent identifier
or submission timestamp in the specified schema. Preserve the records until
their provenance can be assessed. Repeated records may affect later statistical
independence and train/test separation; a duplicate-handling policy is needed
before modeling. Do not silently drop them or assume they are independent.

## Exact schema validation

**Objective:** compare every column with the user-specified schema and require
2,613 rows, 30 columns, and five items per prefix. Any difference stops execution.
The strings below specify expected existing columns; they do not add variables.
''')
code('''
demographic_columns = ["Gender", "Age", "University Type", "Academic Level", "Department/Discipline"]
expected_items = {
    "AI Usage": [
        "I use generative AI tools regularly for academic purposes.",
        "I use AI tools for assignment writing.",
        "I use AI tools for study planning.",
        "I use AI tools for research-related tasks.",
        "I depend on AI tools to complete academic work faster.",
    ],
    "Cognitive Dependence": [
        "I feel uncomfortable completing academic tasks without AI tools.",
        "I rely on AI before thinking independently.",
        "AI tools have become essential to my academic workflow.",
        "I use AI tools even for simple academic decisions.",
        "I feel less confident working without AI assistance.",
    ],
    "Trust in AI": [
        "I trust AI-generated academic responses.",
        "AI tools usually provide reliable information.",
        "I rarely verify AI-generated answers before using them.",
        "I believe AI tools make better academic suggestions than I can myself.",
        "I trust AI recommendations for academic decision-making.",
    ],
    "Critical Thinking": [
        "Using AI tools reduces my need to think deeply.",
        "I analyze less when using AI-generated responses.",
        "I prefer AI explanations over conducting my own research.",
        "AI tools reduce my independent problem-solving efforts.",
        "I rely more on AI-generated ideas than my own thinking.",
    ],
    "Academic Decision-Making": [
        "AI tools influence my academic decisions.",
        "I use AI suggestions for study-related decisions.",
        "AI tools help me choose research topics or project ideas.",
        "I use AI recommendations to improve academic performance.",
        "AI tools positively affect my academic decision-making process.",
    ],
}
expected_columns = demographic_columns + [
    f"{prefix} [{item}]"
    for prefix, items in expected_items.items()
    for item in items
]
missing_columns = [column for column in expected_columns if column not in df.columns]
unexpected_columns = [column for column in df.columns if column not in expected_columns]
print("Expected shape:", (2613, 30))
print("Actual shape:", df.shape)
print("Missing expected columns:", missing_columns)
print("Unexpected columns:", unexpected_columns)
print("Column order matches:", df.columns.tolist() == expected_columns)
if df.shape != (2613, 30) or df.columns.tolist() != expected_columns:
    raise ValueError("Dataset structure differs from the supplied schema. Stop and report the output above.")

survey_columns = []
for prefix in expected_items:
    matched = [column for column in df.columns if column.startswith(prefix + " [")]
    print(f"{prefix}: {len(matched)} items")
    if len(matched) != 5:
        raise ValueError(f"Expected exactly five items for {prefix}; found {len(matched)}.")
    survey_columns.extend(matched)
print("Exact schema validation: PASS")
''')
markdown('''
**Reading the output:** a PASS means both the complete ordered column names and
the row/column counts match. Prefix counts check the five survey groups without
renaming or encoding any column.

## Invalid-value checks after inspecting the responses

**Objective:** compare the observed labels with the five labels supplied in the
project specification, now that all unique responses have been printed. Check
whether Age is numeric and whether values are finite positive whole numbers.
These checks do not establish enrollment eligibility; no age eligibility rule
or demographic codebook was supplied. Nominal demographic labels are reported
as observed, not converted into ordered numbers.
''')
code('''
import numpy as np

expected_likert_labels = {
    "Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"
}
likert_audit = []
for column in survey_columns:
    observed = set(df[column].dropna().unique())
    likert_audit.append({
        "column": column,
        "unique_nonmissing": len(observed),
        "unexpected_labels": sorted(observed - expected_likert_labels),
        "specified_labels_not_observed": sorted(expected_likert_labels - observed),
        "invalid_nonmissing_count": int((df[column].notna() & ~df[column].isin(expected_likert_labels)).sum()),
        "exact_label_set_match": observed == expected_likert_labels,
    })
likert_audit = pd.DataFrame(likert_audit)
print("Likert checks (no encoding performed):")
print(likert_audit.to_string(index=False))

age_numeric = pd.to_numeric(df["Age"], errors="coerce")
age_conversion_failures = int((df["Age"].notna() & age_numeric.isna()).sum())
invalid_age = age_numeric.notna() & (
    ~np.isfinite(age_numeric) | (age_numeric <= 0) | (age_numeric % 1 != 0)
)
print("\\nAge already has numeric dtype:", pd.api.types.is_numeric_dtype(df["Age"]))
print("Nonmissing Age values failing numeric conversion:", age_conversion_failures)
print("Nonfinite/nonpositive/noninteger Age values:", int(invalid_age.sum()))
print("Observed Age values:", sorted(age_numeric.dropna().unique().tolist()))
print("Age range:", age_numeric.min(), "to", age_numeric.max())
print("Distinct Department/Discipline labels:", df["Department/Discipline"].nunique())

if not likert_audit["exact_label_set_match"].all():
    raise ValueError("Observed Likert label sets differ from the specified sets. Stop for review.")
print("All 25 survey columns contain exactly the five specified labels: PASS")
''')
markdown('''
**Reading the output:** passing these checks means no violations of the stated
label sets or basic Age format were detected. It cannot prove that a response is
truthful or that the sampling process is sound. Department labels such as `CSE`
and `Computer Science and Engineering`, or `EEE` and `Electrical and Electronic
Engineering`, may overlap in meaning; confirm their definitions before merging.

## Phase 1 findings and saved audit artifacts

**Objective:** save reproducible audit tables and a report derived from the
executed checks. The original CSV remains unchanged. No cleaned dataset,
composite scores, statistical tests, or trained models are produced in Phase 1.
''')
code('''
output_dir = Path("outputs") / "phase1"
output_dir.mkdir(parents=True, exist_ok=True)
column_audit = pd.DataFrame({
    "column": df.columns,
    "dtype": df.dtypes.astype(str).to_numpy(),
    "missing_count": missing_counts.to_numpy(),
    "unique_nonmissing_count": df.nunique().to_numpy(),
})
column_audit.to_csv(output_dir / "column_audit.csv", index=False)
likert_audit.to_csv(output_dir / "likert_value_audit.csv", index=False)
frequency_tables = []
for column in df.columns:
    counts = df[column].value_counts(dropna=False).rename_axis("value").reset_index(name="count")
    counts.insert(0, "column", column)
    frequency_tables.append(counts)
pd.concat(frequency_tables, ignore_index=True).to_csv(output_dir / "value_counts.csv", index=False)

report = f"""# Phase 1 — Dataset audit

Project: AI Dependency and Cognitive Offloading Among University Students:
An Explainable Machine Learning Study

- File: `{dataset_path.name}`. The filename omits the `(1)` suffix in the original request.
- Shape: {df.shape[0]:,} rows × {df.shape[1]} columns; exact supplied schema and order match.
- Survey groups: five groups with five items each.
- Missing cells: {int(missing_counts.sum())}.
- Blank text values: {int(blank_counts.sum())}; surrounding-whitespace values: {int(whitespace_counts.sum())}.
- Exact duplicate rows beyond first occurrences: {duplicate_count:,} ({duplicate_count / len(df):.2%}).
- Rows in duplicate groups, including first occurrences: {duplicate_participants:,}.
- Distinct complete response patterns: {unique_record_count:,}.
- Age: numeric `{df['Age'].dtype}`, observed range {age_numeric.min()}–{age_numeric.max()}.
- Age conversion failures: {age_conversion_failures}; basic Age-format violations: {int(invalid_age.sum())}.
- All 25 survey columns contain exactly Strongly Disagree, Disagree, Neutral, Agree, and Strongly Agree.
- Unexpected nonmissing Likert responses: {int(likert_audit['invalid_nonmissing_count'].sum())}.
- Gender: {', '.join(sorted(df['Gender'].unique()))}.
- University Type: {', '.join(sorted(df['University Type'].unique()))}.
- Academic Level: {', '.join(sorted(df['Academic Level'].unique()))}.
- Department/Discipline: {df['Department/Discipline'].nunique()} distinct labels; see value_counts.csv for all labels and frequencies.

## Issues requiring attention in later phases

Matching records do not establish repeated respondents. No respondent identifier
or timestamp is available to resolve their origin. Keep all records in this audit.
Determine a documented policy before inference and splitting for machine learning;
overlapping repeated records could produce optimistic test performance.

Department names include possible abbreviation/full-name variants (CSE versus
Computer Science and Engineering; EEE versus Electrical and Electronic Engineering).
No categories have been merged without confirming their meaning.

No demographic codebook, eligibility rules, or sampling/provenance documentation
was supplied. Basic format checks cannot validate those properties or independence.
All responses are self-reports. No causal, cognitive-ability, or diagnostic
conclusions follow from this audit. Do not publish respondent-level records
or notebook previews without checking the dataset's sharing permissions.

Phase 1 is complete. No encoding, row deletion, index construction, or modeling
has been performed. The observed labels support the specified encoding in Phase 2.
"""
(output_dir / "audit_report.md").write_text(report, encoding="utf-8")
print(report)
print("Audit artifacts saved in:", output_dir.resolve())
''')
markdown('''
**Interpretation:** the schema and Likert labels match the specification.
The duplicate records and potentially overlapping department labels need
documented handling later. These audit findings do not answer the research
questions; those require the subsequent reliability, statistical, and modeling
phases. This notebook deliberately stops after Phase 1.
''')


def main():
    import os
    os.chdir(ROOT)
    namespace = {"__name__": "__main__"}
    execution_count = 0
    failure = None
    for cell in cells:
        if cell["cell_type"] != "code":
            continue
        execution_count += 1
        cell["execution_count"] = execution_count
        captured = StringIO()
        try:
            with redirect_stdout(captured):
                exec(compile(cell["source"], f"phase1_cell_{execution_count}", "exec"), namespace)
        except Exception as error:
            failure = error
            cell["outputs"].append({"output_type": "error", "ename": type(error).__name__,
                                    "evalue": str(error), "traceback": traceback.format_exc().splitlines()})
        if captured.getvalue():
            cell["outputs"].insert(0, {"output_type": "stream", "name": "stdout", "text": captured.getvalue()})
        if failure:
            break
    notebook = {
        "cells": [dict(cell, id=f"phase1-{i:02d}") for i, cell in enumerate(cells, start=1)],
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": namespace["platform"].python_version()},
        },
        "nbformat": 4, "nbformat_minor": 5,
    }
    destination = ROOT / "AI_Dependency_Study.ipynb"
    destination.write_text(json.dumps(notebook, indent=1, ensure_ascii=False), encoding="utf-8")
    if failure:
        raise failure
    print(f"Executed {execution_count} code cells successfully: {destination}")
    print(namespace["report"])


if __name__ == "__main__":
    main()
